[package]
name = "route_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
csv = "1.3.1"
indicatif = "0.17.11"
netcdf = "0.11.0"
num_cpus = "1.16.0"
rusqlite = "0.35.0"
serde = "1.0.219"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
